version: '3.8'

services:
  postgres-server:
    image: postgres:12
    container_name: spring_redis_db_container
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: spring_redis_db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis-server:
    image: redis
    container_name: redis_container
    ports:
      - "6379:6379"

  spring-redis-api:
    build: .
    container_name: spring_redis_api_container
    ports:
      - "8080:8080"
    depends_on:
      - postgres-server
      - redis-server
    links:
      - postgres-server
      - redis-server
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      PG_HOST: ${PG_HOST}
      REDIS_HOST: ${REDIS_HOST}

volumes:
  postgres_data: